import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";

export const catppuccinLightTheme: { [key: string]: React.CSSProperties } = {
  ...vscDarkPlus,
  'code[class*="language-"]': {
    color: '#4c4f69',
    background: 'none',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    textAlign: 'left' as const,
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    color: '#4c4f69',
    background: '#eff1f5',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    textAlign: 'left' as const,
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    tabSize: 2,
    borderRadius: '0.5rem',
    padding: '1rem',
    margin: 0,
    overflow: 'auto',
  },
  comment: { color: '#9ca0af', fontStyle: 'italic' },
  prolog: { color: '#9ca0af', fontStyle: 'italic' },
  doctype: { color: '#9ca0af', fontStyle: 'italic' },
  cdata: { color: '#9ca0af', fontStyle: 'italic' },
  punctuation: { color: '#04a5e5' },
  constant: { color: '#fe640b' },
  tag: { color: '#1e66f5' },
  property: { color: '#04a5e5' },
  boolean: { color: '#d20f39' },
  number: { color: '#fe640b' },
  selector: { color: '#40a02b' },
  'attr-name': { color: '#df8e1d' },
  string: { color: '#40a02b' },
  char: { color: '#40a02b' },
  builtin: { color: '#df8e1d' },
  inserted: { color: '#40a02b' },
  operator: { color: '#04a5e5' },
  entity: { color: '#8839ef', cursor: 'help' as const },
  url: { color: '#04a5e5' },
  symbol: { color: '#d20f39' },
  atrule: { color: '#8839ef' },
  attrValue: { color: '#40a02b' },
  keyword: { color: '#8839ef' },
  regex: { color: '#df8e1d' },
  important: { color: '#d20f39', fontWeight: 'bold' as const },
  bold: { fontWeight: 'bold' as const },
  italic: { fontStyle: 'italic' as const },
  variable: { color: '#d20f39' },
  'unit': { color: '#fe640b' },
  'deleted': { color: '#d20f39', textDecoration: 'line-through' as const },
  'tag .punctuation': { color: '#1e66f5' },
  'script .punctuation': { color: '#04a5e5' },
  'attr-equals': { color: '#04a5e5' },
  'script .tag .punctuation': { color: '#1e66f5' },
  'namespace': { color: '#fe640b', opacity: 0.7 },
};

export const catppuccinDarkTheme: { [key: string]: React.CSSProperties } = {
  ...vscDarkPlus,
  'code[class*="language-"]': {
    color: '#cdd6f4',
    background: 'none',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    textAlign: 'left' as const,
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    color: '#cdd6f4',
    background: '#1e1e2e',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    textAlign: 'left' as const,
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    lineHeight: '1.5',
    tabSize: 2,
    borderRadius: '0.5rem',
    padding: '1rem',
    margin: 0,
    overflow: 'auto',
  },
  comment: { color: '#6c7086', fontStyle: 'italic' },
  prolog: { color: '#6c7086', fontStyle: 'italic' },
  doctype: { color: '#6c7086', fontStyle: 'italic' },
  cdata: { color: '#6c7086', fontStyle: 'italic' },
  punctuation: { color: '#89dceb' },
  constant: { color: '#fab387' },
  tag: { color: '#89dceb' },
  property: { color: '#89dceb' },
  boolean: { color: '#f38ba8' },
  number: { color: '#fab387' },
  selector: { color: '#a6e3a1' },
  'attr-name': { color: '#f9e2af' },
  string: { color: '#a6e3a1' },
  char: { color: '#a6e3a1' },
  builtin: { color: '#f9e2af' },
  inserted: { color: '#a6e3a1' },
  operator: { color: '#89dceb' },
  entity: { color: '#f5c2e7', cursor: 'help' as const },
  url: { color: '#89dceb' },
  symbol: { color: '#f38ba8' },
  atrule: { color: '#cba6f7' },
  attrValue: { color: '#a6e3a1' },
  keyword: { color: '#cba6f7' },
  regex: { color: '#f9e2af' },
  important: { color: '#f38ba8', fontWeight: 'bold' as const },
  bold: { fontWeight: 'bold' as const },
  italic: { fontStyle: 'italic' as const },
  variable: { color: '#f38ba8' },
  'unit': { color: '#fab387' },
  'deleted': { color: '#f38ba8', textDecoration: 'line-through' as const },
  'tag .punctuation': { color: '#89dceb' },
  'script .punctuation': { color: '#89dceb' },
  'attr-equals': { color: '#89dceb' },
  'script .tag .punctuation': { color: '#89dceb' },
  'namespace': { color: '#fab387', opacity: 0.7 },
};
